version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: loja_schema
      MYSQL_USER: vinicius
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"

  web:
    image: tomcat:8
    ports:
      - "8080:8080"
